refDes: DAQ000
ip: localhost
wsPort: 8001
description: Testing DAQ node
enabled: false

modules:
  - slotId: 1
    moduleModelNumber: NI-9265
    description: 4-ch analog current output
    ioMode: output
    enabled: true
    sampleRateHz: 1000
  - slotId: 2
    moduleModelNumber: NI-9208
    description: 16-ch analog current input
    ioMode: input
    enabled: true
    sampleRateHz: 100
  - slotId: 3
    moduleModelNumber: NI-9474
    description: 8-ch sourcing digital output
    ioMode: output
    enabled: true
    sampleRateHz: 1000
