values:
    CYCLE_TIME: 0.01
    LIM-CPT01-HIGH: 450
    LIM-CPT01-LOW: 50
    SEQ-CUTOFF-T: 3
    SEQ-IGN-LEAD: 0.5
    SM-firingSequence-STATE: 0
    SM-firingSequence-TARGET: 0
    T-TIME: 3.47999999999997
