name: Test panel
version: 1
objects:
  - id: sensor_1775091859475_6637
    type: sensor
    refDes: OT-01
    units: Deg F
    gridX: 19
    gridY: 6
  - id: node_1775091861441_6209
    type: node
    gridX: 21
    gridY: 14
  - id: sensor_1775091863704_3007
    type: sensor
    refDes: OT-02
    units: Deg F
    gridX: 23
    gridY: 13
  - id: sensor_1775091865101_9104
    type: sensor
    refDes: OT-03
    units: Deg F
    gridX: 11
    gridY: 17
  - id: sensor_1775091866277_2714
    type: sensor
    refDes: CTR001-uptime
    units: s
    gridX: 35
    gridY: 21
  - id: sensor_1775091867852_4019
    type: sensor
    refDes: OT-04
    units: Deg F
    gridX: 29
    gridY: 17
  - id: sensor_1775091955034_7249
    type: sensor
    refDes: LCC-01-01
    units: Pounds
    gridX: 27
    gridY: 9
  - id: graph_1775174926738_8097
    type: graph
    name: Control Node
    gridX: 42
    gridY: 3
    gridW: 30
    gridH: 20
    showLeftSidebar: true
    lines:
      - refDes: CTR001-uptime
        color: "#4e9f3d"
        yAxis: 4
      - refDes: CTR001-daqConnected
        color: "#4fc3f7"
        yAxis: 2
      - refDes: CTR001-wcConnected
        color: "#ff7043"
        yAxis: 2
      - refDes: CTR001-loopTime
        color: "#ffd54f"
      - refDes: CTR001-restart
        color: "#ba68c8"
        yAxis: 2
connections:
  - id: conn_1775091870218_2314
    fromId: sensor_1775091865101_9104
    fromPort: bottom
    toId: sensor_1775091867852_4019
    toPort: bottom
  - id: conn_1775091872573_6918
    fromId: sensor_1775091866277_2714
    fromPort: bottom
    toId: sensor_1775091867852_4019
    toPort: bottom
  - id: conn_1775091875613_6657
    fromId: node_1775091861441_6209
    fromPort: bottom
    toId: sensor_1775091865101_9104
    toPort: bottom
  - id: conn_1775091877289_6622
    fromId: node_1775091861441_6209
    fromPort: left
    toId: sensor_1775091863704_3007
    toPort: bottom
  - id: conn_1775091879234_4901
    fromId: node_1775091861441_6209
    fromPort: top
    toId: sensor_1775091859475_6637
    toPort: bottom
